export const CONNECT = "CONNECT";
export const UPDATE_SELECTED_ADDRESS = "UPDATE_SELECTED_ADDRESS";

export const TOGGLE_MENU = "TOGGLE_MENU";

export const CHANGE_SCREEN_SIZE = "CHANGE_SCREEN_SIZE";
