export const CONNECT = "CONNECT";
export const UPDATE_SELECTED_ADDRESS = "UPDATE_SELECTED_ADDRESS";
export const UPDATE_WALLET_BALANCE = "UPDATE_WALLET_BALANCE";

export const TOGGLE_MENU = "TOGGLE_MENU";
export const TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION";
export const TOGGLE_IN_TRANSACTION = "TOGGLE_IN_TRANSACTION";

export const CHANGE_SCREEN_SIZE = "CHANGE_SCREEN_SIZE";

export const UPDATE_VAULTS = "UPDATE_VAULTS";

export const UPDATE_REWARDS_TOKEN = "UPDATE_REWARDS_TOKEN";
export const UPDATE_HATS_PRICE = "UPDATE_HATS_PRICE";

export const UPDATE_LIQUIDITY_POOL = "UPDATE_LIQUIDITY_POOL";

export const UPDATE_WITHDRAW_SAFETY_PERIOD = "UPDATE_WITHDRAW_SAFETY_PERIOD";
