export const CONNECT = "CONNECT";
export const UPDATE_SELECTED_ADDRESS = "UPDATE_SELECTED_ADDRESS";
export const UPDATE_WALLET_BALANCE = "UPDATE_WALLET_BALANCE";

export const TOGGLE_MENU = "TOGGLE_MENU";
export const TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION";
export const TOGGLE_IN_TRANSACTION = "TOGGLE_IN_TRANSACTION";
export const UPDATE_TRANSACTION_HASH = "UPDATE_TRANSACTION_HASH";

export const CHANGE_SCREEN_SIZE = "CHANGE_SCREEN_SIZE";

export const UPDATE_VAULTS = "UPDATE_VAULTS";

export const UPDATE_REWARDS_TOKEN = "UPDATE_REWARDS_TOKEN";
export const UPDATE_HATS_PRICE = "UPDATE_HATS_PRICE";

export const UPDATE_WITHDRAW_SAFETY_PERIOD = "UPDATE_WITHDRAW_SAFETY_PERIOD";

export const TOGGLE_SUBMITTING_VULNERABILITY = "TOGGLE_SUBMITTING_VULNERABILITY"

export const UPDATE_AIRDROP_DATA = "UPDATE_AIRDROP_DATA";
